#!/usr/bin/env python3
"""
Git and GitHub Operations
Handles branch creation, commits, and PR creation
"""

import subprocess
import os
from pathlib import Path


class GitOperations:
    def __init__(self, repo_name, repo_path=None):
        """
        Initialize Git operations for a repository
        
        Args:
            repo_name: Name of the GitHub repository (e.g., "test-ai-project")
            repo_path: Local path to repo (optional, will clone if not exists)
        """
        self.repo_name = repo_name
        self.repo_path = repo_path or self._get_or_clone_repo()
        
    def _get_or_clone_repo(self):
        """Get local repo path or clone if doesn't exist"""
        # Use ~/repos directory for all cloned repos
        repos_dir = Path.home() / "repos"
        repos_dir.mkdir(exist_ok=True)
        
        repo_path = repos_dir / self.repo_name
        
        if not repo_path.exists():
            # Clone the repository
            print(f"📥 Cloning {self.repo_name}...")
            result = subprocess.run(
                ['gh', 'repo', 'clone', self.repo_name, str(repo_path)],
                capture_output=True,
                text=True
            )
            if result.returncode != 0:
                raise Exception(f"Failed to clone repo: {result.stderr}")
        
        return str(repo_path)
    
    def create_branch(self, branch_name):
        """Create and checkout a new git branch"""
        print(f"🌿 Creating branch: {branch_name}")
        
        # Ensure we're on main and up to date
        self._run_git(['checkout', 'main'])
        self._run_git(['pull', 'origin', 'main'])
        
        # Create and checkout new branch
        self._run_git(['checkout', '-b', branch_name])
        
        return branch_name
    
    def write_files(self, files):
        """
        Write generated files to repository
        
        Args:
            files: List of dicts with 'path' and 'content' keys
        """
        print(f"📝 Writing {len(files)} file(s)...")
        
        for file_data in files:
            file_path = Path(self.repo_path) / file_data['path']
            
            # Create directories if needed
            file_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Write file
            file_path.write_text(file_data['content'])
            print(f"  ✓ {file_data['path']}")
    
    def commit_and_push(self, ticket_id, description, branch_name):
        """Commit all changes and push to remote"""
        print(f"💾 Committing changes...")
        
        # Stage all changes
        self._run_git(['add', '.'])
        
        # Create commit message
        commit_msg = f"{ticket_id}: {description}\n\nGenerated by AI Dev Assistant"
        
        # Commit
        self._run_git(['commit', '-m', commit_msg])
        
        # Push to remote
        print(f"⬆️  Pushing to origin/{branch_name}...")
        self._run_git(['push', '-u', 'origin', branch_name])
        
        return True
    
    def create_pull_request(self, ticket_id, description, branch_name, files):
        """Create a GitHub Pull Request"""
        print(f"🔀 Creating Pull Request...")
        
        # Build PR body
        file_list = '\n'.join([f"- {f['path']}" for f in files])
        
        pr_body = f"""## {ticket_id}

### 📝 Description
{description}

### 📄 Generated Files
{file_list}

### 🤖 Generated By
AI Dev Assistant

### ✅ Review Checklist
- [ ] Code quality verified
- [ ] Functionality tested
- [ ] Design/UI approved
- [ ] Ready to merge

---
*This PR was automatically generated by AI Dev Assistant*
"""
        
        # Create PR using gh CLI
        result = subprocess.run(
            [
                'gh', 'pr', 'create',
                '--title', f"{ticket_id}: {description}",
                '--body', pr_body,
                '--base', 'main',
                '--head', branch_name
            ],
            cwd=self.repo_path,
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            raise Exception(f"Failed to create PR: {result.stderr}")
        
        # Extract PR URL from output
        pr_url = result.stdout.strip().split('\n')[-1]
        
        print(f"✅ PR created: {pr_url}")
        return pr_url
    
    def _run_git(self, args):
        """Run a git command in the repo directory"""
        result = subprocess.run(
            ['git'] + args,
            cwd=self.repo_path,
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            raise Exception(f"Git command failed: {result.stderr}")
        
        return result.stdout


def test_git_operations():
    """Test function"""
    git_ops = GitOperations('test-ai-project')
    
    # Test branch creation
    branch = git_ops.create_branch('feature/TEST-001')
    print(f"Created branch: {branch}")
    
    # Test file writing
    test_files = [
        {
            'path': 'test.html',
            'content': '<h1>Test</h1>'
        }
    ]
    git_ops.write_files(test_files)
    
    # Would commit and push in real scenario
    print("✅ Git operations test passed!")


if __name__ == '__main__':
    test_git_operations()
